export type Language = "ca" | "es" | "en"

export const languages: { code: Language; label: string }[] = [
  { code: "ca", label: "CA" },
  { code: "es", label: "ES" },
  { code: "en", label: "EN" },
]

export const translations = {
  ca: {
    nav: { method: "Mètode", services: "Serveis", technicalOffice: "Oficina Tècnica", gallery: "Abans i Després", about: "Qui Som", contact: "Contacte", quote: "Pressupost" },
    hero: { title: "", subtitle: "NOVUM: Gestió personalitzada i execució tècnica. Coordinem cada detall de la teva reforma perquè tu només gaudeixis del resultat.", ctaPrimary: "Pressupost sense compromís", ctaSecondary: "El nostre mètode" },
    method: { eyebrow: "El Nostre Mètode", title: "Servei Clau en Mà", subtitle: "Ens encarreguem de tot el procés de principi a fi. Tu només has de gaudir del resultat.", steps: [ { title: "Gestió", description: "Tramitem tots els permisos i llicències necessaris. Ens encarreguem de la burocràcia perquè tu no t'hagis de preocupar." }, { title: "Supervisió", description: "Un cap d'obra dedicat supervisa cada fase del projecte, garantint qualitat i compliment de terminis." }, { title: "Finalització", description: "Neteja integral postobra inclosa. Lliurem el teu espai llest per viure, sense sorpreses ni extres." } ] },
    services: { eyebrow: "Especialitats", title: "Els Nostres Serveis", subtitle: "Solucions integrals per a cada aspecte de la teva reforma.", items: [ { title: "Pladur", description: "Solucions a pladur per als teus espais.", image: "/images/trabajos pladur.png" }, { title: "Electricitat", description: "Instal·lacions elèctriques completes i certificades.", image: "/images/service-electrical.png" }, { title: "Lampisteria", description: "Instal·lacions d'aigua, sanejament.", image: "/images/service-plumbing.png" }, { title: "Alumini", description: "Finestres, portes i tancaments d'alumini.", image: "/images/service-aluminium.jpg" }, { title: "Fusteria", description: "Mobles a mida, armaris i fusteria d'interior.", image: "/images/service-carpentry.jpg" }, { title: "Cuines", description: "Disseny i instal·lació de cuines completes.", image: "/images/service-interiors.jpg" }, { title: "Paleta", description: "Treballem amb professionals experimentats del sector.", image: "/images/service-masonry.jpg" }, { title: "Climatització", description: "Instal·lacions de clima.", image: "/images/service-hvac.png" }, { title: "Neteja", description: "Neteja professional de fi d'obra inclosa.", image: "/images/service-cleaning..jpg" } ] },
    technicalOffice: { eyebrow: "Suport Professional", title: "Oficina Tècnica", description: "Comptem amb una xarxa d'arquitectes i enginyers col·laboradors externs que garanteixen el compliment tècnic i legal de cada projecte. No som un estudi d'arquitectura, però treballem colze a colze amb els millors professionals.", features: [ { title: "Arquitectes Externs", description: "Col·laborem amb arquitectes i enginyers col·legiats que supervisen i signen els projectes tècnics necessaris." }, { title: "Projectes Legalitzats", description: "Tots els projectes compleixen amb la normativa vigent. Gestionem llicències, permisos i certificats." }, { title: "Honoraris Transparents", description: "Els honoraris tècnics es pressuposten per separat, sense sorpreses ni costos ocults." } ], stat: "Projectes with professional technical supervision" },
    projects: { eyebrow: "Tipus de Projecte", title: "Reformes per a Cada Espai", subtitle: "Solucions adaptades a la mida del teu habitatge. Consulta'ns per a més detalls i preus.", items: [ { size: "50 m²", title: "Pis 50 m²", description: "Reforma integral ideal per a pisos petits i estudis. Aviat afegirem detalls i preus." }, { size: "80 m²", title: "Pis 80 m²", description: "Reforma completa per a habitatges mitjans. Aviat afegirem detalls i preus." }, { size: "100 m²", title: "Pis 100 m²", description: "Reforma integral per a habitatges amplis. Aviat afegirem detalls i preus." } ], cta: "Demanar informació" },
    gallery: { eyebrow: "Els Nostres Treballs", title: "Abans i Després", subtitle: "Descobreix la transformació real dels nostres projectes de reforma.", before: "Abans", after: "Després", empty: "Aviat publicarem les nostres reformes aquí.", adminLink: "Gestionar galeria" },
    about: { eyebrow: "Sobre Nosaltres", title: "Qui Som", paragraphs: [ "Darrere d'Elecfont AS23 hi ha un equip familiar i professional amb més de 10 anys d'experiència en instal·lacions d'electricitat, lampisteria i climatització.", "Vam crear NOVUM, el nostre departament exclusiu de reformes integrals.", "Combinem l'experiència tècnica amb la transparencia i el disseny." ], highlights: [ "Més de 10 anys d'experiència", "Equip propi", "Pressupostos tancats", "Garantia de qualitat", "Servei postobra inclòs" ] },
    contact: { eyebrow: "Contacte", title: "Fem el primer pas?", subtitle: "Explica'ns el teu projecte i et prepararem un pressupost personalitzat sense cap compromís.", location: "Ubicació", locationValue: "Badalona", phone: "Telèfon", email: "Correu electrònic", form: { name: "Nom", namePlaceholder: "El teu nom complet", phone: "Telèfon", email: "Correu electrònic", town: "Població", townPlaceholder: "La teva ciutat o poble", message: "Missatge", messagePlaceholder: "Explica'ns el teu projecte o idea", submit: "Demanar pressupost", submitting: "Enviant...", successTitle: "Missatge enviat!", successText: "Ens posarem en contacte amb tu molt aviat.", disclaimer: "La teva informació serà tractada amb total confidencialitat." } },
    footer: { tagline: "Reformes integrals amb garantia tècnica.", navTitle: "Navegació", contactTitle: "Contacte", rights: "Tots els drets reservats.", privacy: "Política de privacitat", legal: "Avís legal" }
  },
  es: {
    nav: { method: "Método", services: "Servicios", technicalOffice: "Oficina Técnica", gallery: "Antes y Después", about: "Quiénes Somos", contact: "Contacto", quote: "Presupuesto" },
    hero: { title: "", subtitle: "NOVUM: Gestión personalizada y ejecución técnica. Coordinamos cada detalle de tu reforma para que tú solo disfrutes del resultado.", ctaPrimary: "Presupuesto sin compromiso", ctaSecondary: "Nuestro Método" },
    method: { eyebrow: "Nuestro Método", title: "Servicio Llave en Mano", subtitle: "Nos encargamos de todo el proceso de principio a fin. Tú solo tienes que disfrutar del resultado.", steps: [ { title: "Gestión", description: "Tramitamos todos los permisos y licencias necesarios." }, { title: "Supervisión", description: "Un jefe de obra dedicado supervisa cada fase del proyecto." }, { title: "Finalización", description: "Limpieza integral post-obra incluida." } ] },
    services: { eyebrow: "Especialidades", title: "Nuestros Servicios", subtitle: "Soluciones integrales para cada aspecto de tu reforma.", items: [ { title: "Pladur", description: "Soluciones en pladur para tus espacios.", image: "/images/trabajos pladur.png" }, { title: "Electricidad", description: "Instalaciones eléctricas completas y certificadas.", image: "/images/service-electrical.png" }, { title: "Fontanería", description: "Instalaciones de agua, saneamiento.", image: "/images/service-plumbing.png" }, { title: "Aluminio", description: "Ventanas, puertas y cerramientos de aluminio.", image: "/images/service-aluminium.jpg" }, { title: "Carpintería", description: "Muebles a medida, armarios y carpintería de interior.", image: "/images/service-carpentry.jpg" }, { title: "Cocinas", description: "Diseño e instalación de cocinas completas.", image: "/images/service-interiors.jpg" }, { title: "Albañilería", description: "Trabajamos con profesionales experimentados en el sector.", image: "/images/service-masonry.jpg" }, { title: "Climatización", description: "Instalaciones de clima.", image: "/images/service-hvac.png" }, { title: "Limpieza", description: "Limpieza profesional de fin de obra incluida.", image: "/images/service-cleaning..jpg" } ] },
    technicalOffice: { eyebrow: "Respaldo Profesional", title: "Oficina Técnica", description: "Contamos con una red de arquitectos e ingenieros colaboradores externos que garantizan el cumplimiento técnico y legal de cada proyecto.", features: [ { title: "Arquitectos Externos", description: "Colaboramos con arquitectos e ingenieros colegiados." }, { title: "Proyectos Legalizados", description: "Todos los proyectos cumplen con la normativa vigente." }, { title: "Honorarios Transparentes", description: "Los honorarios técnicos se presupuestan por separado." } ], stat: "Proyectos con supervisión técnica profesional" },
    projects: { eyebrow: "Tipo de Proyecto", title: "Reformas para Cada Espacio", subtitle: "Soluciones adaptadas al tamaño de tu vivienda. Consúltanos para más detalles y precios.", items: [ { size: "50 m²", title: "Piso 50 m²", description: "Reforma integral ideal para pisos pequeños y estudios." }, { size: "80 m²", title: "Piso 80 m²", description: "Reforma completa para viviendas medianas." }, { size: "100 m²", title: "Piso 100 m²", description: "Reforma integral para viviendas amplias." } ], cta: "Pedir información" },
    gallery: { eyebrow: "Nuestros Trabajos", title: "Antes y Después", subtitle: "Descubre la transformación real de nuestros proyectos de reforma.", before: "Antes", after: "Después", empty: "Pronto publicaremos nuestras reformas aquí.", adminLink: "Gestionar galería" },
    about: { eyebrow: "Sobre Nosotros", title: "Quiénes Somos", paragraphs: [ "Detrás de Elecfont AS23 hay un equipo familiar y profesional con más de 10 años de experiencia.", "Creamos NOVUM, nuestro departamento exclusivo de reformas integrales.", "Combinamos experiencia técnica, transparencia y diseño." ], highlights: [ "Más de 10 años de experiencia", "Equipo propio", "Presupuestos cerrados", "Garantía de calidad", "Servicio post-obra incluido" ] },
    contact: { eyebrow: "Contacto", title: "¿Damos el primer paso?", subtitle: "Cuéntanos tu proyecto y te prepararemos un presupuesto personalizado.", location: "Ubicación", locationValue: "Badalona", phone: "Teléfono", email: "Email", form: { name: "Nombre", namePlaceholder: "Tu nombre completo", phone: "Teléfono", email: "Email", town: "Población", townPlaceholder: "Tu ciudad o pueblo", message: "Mensaje", messagePlaceholder: "Cuéntanos tu proyecto o idea", submit: "Solicitar presupuesto", submitting: "Enviando...", successTitle: "¡Mensaje enviado!", successText: "Nos pondremos en contacto contigo pronto.", disclaimer: "Tu información será tratada con confidencialidad." } },
    footer: { tagline: "Reformas integrales con garantía técnica.", navTitle: "Navegación", contactTitle: "Contacto", rights: "Todos los derechos reservados.", privacy: "Política de privacidad", legal: "Aviso legal" }
  },
  en: {
    nav: { method: "Method", services: "Services", technicalOffice: "Technical Office", gallery: "Before & After", about: "About Us", contact: "Contact", quote: "Get a Quote" },
    hero: { title: "", subtitle: "NOVUM: Personalized management and technical execution. We coordinate every detail of your renovation.", ctaPrimary: "Free quote", ctaSecondary: "Our Method" },
    method: { eyebrow: "Our Method", title: "Turnkey Service", subtitle: "We handle the entire process from start to finish.", steps: [ { title: "Management", description: "We process all the necessary permits and licenses." }, { title: "Supervision", description: "A dedicated site manager oversees every phase." }, { title: "Completion", description: "Full post-construction cleaning included." } ] },
    services: { eyebrow: "Specialties", title: "Our Services", subtitle: "Comprehensive solutions for your renovation.", items: [ { title: "Drywall", description: "Drywall solutions for your spaces.", image: "/images/trabajos pladur.png" }, { title: "Electrical", description: "Complete, certified electrical installations.", image: "/images/service-electrical.png" }, { title: "Plumbing", description: "Water, drainage installations.", image: "/images/service-plumbing.png" }, { title: "Aluminum", description: "Aluminum windows, doors, and enclosures.", image: "/images/service-aluminium.jpg" }, { title: "Carpentry", description: "Custom furniture, wardrobes and interior carpentry.", image: "/images/service-carpentry.jpg" }, { title: "Kitchens", description: "Design and installation of complete kitchens.", image: "/images/service-interiors.jpg" }, { title: "Masonry", description: "We work with experienced professionals.", image: "/images/service-masonry.jpg" }, { title: "Air Conditioning", description: "HVAC systems.", image: "/images/service-hvac.png" }, { title: "Cleaning", description: "Professional end-of-construction cleaning.", image: "/images/service-cleaning..jpg" } ] },
    technicalOffice: { eyebrow: "Professional Backing", title: "Technical Office", description: "We have a network of external architect and engineer partners.", features: [ { title: "External Architects", description: "We collaborate with registered architects." }, { title: "Legalized Projects", description: "All projects comply with regulations." }, { title: "Transparent Fees", description: "Technical fees are quoted separately." } ], stat: "Projects with professional technical supervision" },
    projects: { eyebrow: "Project Type", title: "Renovations for Every Space", subtitle: "Solutions tailored to the size of your home.", items: [ { size: "50 m²", title: "50 m² Flat", description: "Full renovation ideal for small flats." }, { size: "80 m²", title: "80 m² Flat", description: "Complete renovation for mid-sized homes." }, { size: "100 m²", title: "100 m² Flat", description: "Full renovation for spacious homes." } ], cta: "Request information" },
    gallery: { eyebrow: "Our Work", title: "Before & After", subtitle: "Discover the real transformation of our projects.", before: "Before", after: "After", empty: "Coming soon.", adminLink: "Manage gallery" },
    about: { eyebrow: "About Us", title: "Who We Are", paragraphs: [ "Behind Elecfont AS23 is a family-run team with over 10 years of experience.", "We created NOVUM, our exclusive full-renovation department.", "We combine technical expertise, transparency and design." ], highlights: [ "Over 10 years experience", "In-house team", "Fixed quotes", "Quality guarantee", "Post-construction service" ] },
    contact: { eyebrow: "Contact", title: "Shall we take the first step?", subtitle: "Tell us about your project and we'll prepare a quote.", location: "Location", locationValue: "Badalona", phone: "Phone", email: "Email", form: { name: "Name", namePlaceholder: "Your full name", phone: "Phone", email: "Email", town: "Town", townPlaceholder: "Your city or town", message: "Message", messagePlaceholder: "Tell us about your idea", submit: "Request quote", submitting: "Sending...", successTitle: "Message sent!", successText: "We'll get in touch soon.", disclaimer: "Your information will be treated confidentially." } },
    footer: { tagline: "Comprehensive renovations with technical guarantee.", navTitle: "Navigation", contactTitle: "Contact", rights: "All rights reserved.", privacy: "Privacy policy", legal: "Legal notice" }
  }
} as const;