export type Language = "ca" | "es" | "en"

export const languages: { code: Language; label: string }[] = [
  { code: "ca", label: "CA" },
  { code: "es", label: "ES" },
  { code: "en", label: "EN" },
]

export const translations = {
  ca: {
    nav: { method: "Mètode", services: "Serveis", technicalOffice: "Oficina Tècnica", gallery: "Abans i Després", about: "Qui Som", contact: "Contacte", quote: "Pressupost" },
    hero: { title: "", subtitle: "NOVUM: Gestió personalitzada i execució tècnica. Coordinem cada detall de la teva reforma perquè tu només gaudeixis del resultat.", ctaPrimary: "Pressupost sense compromís", ctaSecondary: "El nostre mètode" },
    method: { eyebrow: "El Nostre Mètode", title: "Servei Clau en Mà", subtitle: "Ens encarreguem de tot el procés de principi a fi. Tu només has de gaudir del resultat.", steps: [ { title: "Gestió", description: "Tramitem tots els permisos i llicències necessaris. Ens encarreguem de la burocràcia perquè tu no t'hagis de preocupar." }, { title: "Supervisió", description: "Un cap d'obra dedicat supervisa cada fase del projecte, garantint qualitat i compliment de terminis." }, { title: "Finalització", description: "Neteja integral postobra inclosa. Lliurem el teu espai llest per viure, sense sorpreses ni extres." } ] },
    services: { eyebrow: "Especialitats", title: "Els Nostres Serveis", subtitle: "Solucions integrals per a cada aspecte de la teva reforma.", items: [ { title: "Pladur", description: "Solucions a pladur per als teus espais.", image: "/images/trabajos pladur.png" }, { title: "Electricitat", description: "Instal·lacions elèctriques completes i certificades.", image: "/images/service-electrical.png" }, { title: "Lampisteria", description: "Instal·lacions d'aigua, sanejament.", image: "/images/service-plumbing.png" }, { title: "Alumini", description: "Finestres, portes i tancaments d'alumini.", image: "/images/service-aluminium.jpg" }, { title: "Fusteria", description: "Mobles a mida, armaris i fusteria d'interior.", image: "/images/service-carpentry.jpg" }, { title: "Cuines", description: "Disseny i instal·lació de cuines completes.", image: "/images/service-interiors.jpg" }, { title: "Paleta", description: "Treballem amb professionals experimentats del sector.", image: "/images/service-masonry.jpg" }, { title: "Climatització", description: "Instal·lacions de clima.", image: "/images/service-hvac.png" }, { title: "Neteja", description: "Neteja professional de fi d'obra inclosa.", image: "/images/service-cleaning..jpg" } ] },
    technicalOffice: { eyebrow: "Suport Professional", title: "Oficina Tècnica", description: "Comptem amb una xarxa d'arquitectes i enginyers col·laboradors externs que garanteixen el compliment tècnic i legal de cada projecte.", features: [ { title: "Arquitectes Externs", description: "Col·laborem amb arquitectes i enginyers col·legiats que supervisen i signen els projectes tècnics necessaris." }, { title: "Projectes Legalitzats", description: "Tots els projectes compleixen amb la normativa vigent. Gestionem llicències, permisos i certificats." }, { title: "Honoraris Transparents", description: "Els honoraris tècnics es pressuposten per separat, sense sorpreses ni costos ocults." } ], stat: "Projectes with professional technical supervision" },
    projects: { eyebrow: "Tipus de Projecte", title: "Reformes per a Cada Espai", subtitle: "Solucions adaptades a la mida del teu habitatge. Consulta'ns per a més detalls i preus.", items: [ { size: "50 m²", title: "Pis 50 m²", description: "Reforma integral ideal per a pisos petits i estudis. Aviat afegirem detalls i preus." }, { size: "80 m²", title: "Pis 80 m²", description: "Reforma completa per a habitatges mitjans. Aviat afegirem detalls i preus." }, { size: "100 m²", title: "Pis 100 m²", description: "Reforma integral per a habitatges amplis. Aviat afegirem detalls i preus." } ], cta: "Demanar informació" },
    gallery: { eyebrow: "Els Nostres Treballs", title: "Abans i Després", subtitle: "Descobreix la transformació real dels nostres projectes de reforma.", before: "Abans", after: "Després", empty: "Aviat publicarem les nostres reformes aquí.", adminLink: "Gestionar galeria" },
    about: { eyebrow: "Sobre Nosaltres", title: "Qui Som", paragraphs: [ "Darrere d'Elecfont AS23 hi ha un equip familiar i professional amb més de 10 anys d'experiència en instal·lacions d'electricitat, lampisteria i climatització.", "Vam crear NOVUM, el nostre departament exclusiu de reformes integrals.", "Combinem l'experiència tècnica amb la transparencia i el disseny." ], highlights: [ "Més de 10 anys d'experiència", "Equip propi", "Pressupostos tancats", "Garantia de qualitat", "Servei postobra inclòs" ] },
    contact: { eyebrow: "Contacte", title: "Fem el primer pas?", subtitle: "Explica'ns el teu projecte i et prepararem un pressupost personalitzat sense cap compromís.", location: "Ubicació", locationValue: "Badalona", phone: "Telèfon", email: "Correu electrònic", form: { name: "Nom", namePlaceholder: "El teu nom complet", phone: "Telèfon", email: "Correu electrònic", town: "Població", townPlaceholder: "La teva ciutat o poble", message: "Missatge", messagePlaceholder: "Explica'ns el teu projecte o idea", submit: "Demanar pressupost", submitting: "Enviant...", successTitle: "Missatge enviat!", successText: "Ens posarem en contacte amb tu molt aviat.", disclaimer: "La teva informació serà tractada amb total confidencialitat." } },
    footer: { tagline: "Reformes integrals amb garantia tècnica.", navTitle: "Navegació", contactTitle: "Contacte", rights: "Tots els drets reservats.", privacy: "Política de privacitat", legal: "Avís legal" }
  },
  es: { /* (Aquí iría todo el objeto ES, abreviado para que quepa, usa el que ya tenías) */ },
  en: { /* (Aquí iría todo el objeto EN, usa el que ya tenías) */ }
} as const;

export type TranslationKeys = typeof translations["ca"]